#!/bin/bash
opkg update && opkg install iptables-mod-hashlimit iptables-mod-iprange
wget --no-check-certificate "https://raw.githubusercontent.com/vitoharhari/limitbw/main/limitbw" -O /usr/bin/limitbw && chmod 777 /usr/bin/limitbw
mkdir /root/resipt/
