#!/bin/bash

ver=$(grep VERSION /etc/os-release | cut -d'"' -f2 | awk 'NR==1' | cut -d'.' -f1)

# Updating OPKG
opkg update

# Install needed packages
oIns="opkg install"
pkgname="bash"
if [[ $(opkg list-installed | grep -c "^$pkgname -") == "0" ]]; then $oIns $pkgname; fi
pkgname="iptables-mod-hashlimit"
if [[ $(opkg list-installed | grep -c "^$pkgname -") == "0" ]]; then $oIns $pkgname; fi
pkgname="iptables-mod-iprange"
if [[ $(opkg list-installed | grep -c "^$pkgname -") == "0" ]]; then $oIns $pkgname; fi


if [[ $ver -eq "22" ]]; then
	pkgname="iptables-zz-legacy"
	if [[ $(opkg list-installed | grep -c "^$pkgname -") == "0" ]]; then $oIns $pkgname; fi
else
	pkgname="iptables"
	if [[ $(opkg list-installed | grep -c "^$pkgname -") == "0" ]]; then $oIns $pkgname; fi
fi
cek=$(find /usr/bin/)
if [[ $cek == *"limitbw"* ]]; then
bash /usr/bin/limitbw 3
echo -e "menghapus settingan limitbw"
fi
# Downloading binaries
wget --no-check-certificate "https://raw.githubusercontent.com/vitoharhari/limitbw/main/limitbw" -O /usr/bin/limitbw && chmod 777 /usr/bin/limitbw
mkdir /root/resipt/
touch /root/resipt/ipt.txt
touch /root/resipt/startup
echo "" > /root/resipt/startup
touch /root/resipt/dtb
