#!/bin/bash


clear
ipr2="$(cat /root/resipt/ipt.txt |grep -i ipr | cut -d= -f2 | head -n1)"
spd2="$(cat /root/resipt/ipt.txt |grep -i spd | cut -d= -f2 | head -n1)"
spu2="$(cat /root/resipt/ipt.txt |grep -i spu | cut -d= -f2 | head -n1)"

home() {
echo " Masukkan range ip /ip anda cth: 192.168.1.1-192.168.1.254 atau 192.168.1.1 " 
read -p " default ip: $ipr2 : " ipr
echo " Masukkan limit speed download, ket : dalam KB/s (cth:100)"
read -p " default speed download: $spd2 KB/s : " spd
echo " Masukkan limit speed upload,ket : dalam KB/s (cth:100) "
read -p " default speed download: $spu2 KB/s : " spu
}

hapusset() {
echo " Menghapus settingan limit bandwidth yang lama ..."
sleep 3
clear

#remove old setting iptables

#download
iptables -L --line-numbers | grep DROP | grep destination | cut -b 68-78 > /root/resipt/hasilcekdown
cekdes=$(cat /root/resipt/hasilcekdown)
if [[ $cekdes == "destination" ]]; then
echo " Menghapus limit bw download"
	iptables -D FORWARD -m iprange --dst-range $ipr2 -m hashlimit --hashlimit-above $spd2+kb/s --hashlimit-mode dstip --hashlimit-name vitod -j DROP
else
echo " tidak ada settingan limit yang tersimpan"
fi


#upload
iptables -L --line-numbers | grep DROP | grep source | cut -b 68-73 > /root/resipt/hasilcekup
ceksou=$(cat /root/resipt/hasilcekup)
if [[ $ceksou == "source" ]]; then
	iptables -D FORWARD -m iprange --src-range $ipr2 -m hashlimit --hashlimit-above $spu2+kb/s --hashlimit-mode srcip --hashlimit-name vitou -j DROP
echo " Menghapus limit bw upload"
else
echo " tidak ada settingan limit yang tersimpan"
fi

rm /root/resipt/hasilcekdown
rm /root/resipt/hasilcekup
}

addlim() {
#add limit bw
	#download
	iptables -I FORWARD -m iprange --dst-range $ipr -m hashlimit --hashlimit-above $spd+kb/s --hashlimit-mode dstip --hashlimit-name vitod -j DROP
	#upload
	iptables -I FORWARD -m iprange --src-range $ipr -m hashlimit --hashlimit-above $spu+kb/s --hashlimit-mode srcip --hashlimit-name vitou -j DROP
	echo -e " Limit bandwidth telah berhasil dimasukkan"
}

saveper() {
echo " Menyimpan settingan secara permanen ..."
sleep 2
echo " #download
        iptables -I FORWARD -m iprange --dst-range $ipr -m hashlimit --hashlimit-above $spd+kb/s --hashlimit-mode dstip --hashlimit-name vitod -j DROP
        #upload
        iptables -I FORWARD -m iprange --src-range $ipr -m hashlimit --hashlimit-above $spu+kb/s --hashlimit-mode srcip --hashlimit-name vitou -j DROP" > /root/resipt/startup
sleep 1
chmod 777 /root/resipt/startup
}

exportdtb() {
echo "ipr=$ipr
spd=$spd
spu=$spu" > /root/resipt/ipt.txt
chmod 777 /root/resipt/ipt.txt
}

printset() {
echo " Menampilkan konfigurasi limit bandwidth saat ini ... "
sleep 2
iptables -L --line-numbers | grep DROP | grep destination
iptables -L --line-numbers | grep DROP | grep source
}

startupon() {
echo " Memperbaharui startup di rc.local ..."
sleep 2
sed -i "/exit 0/d" /etc/rc.local
cat <<EOF>> /etc/rc.local
# STARTUP LIMITBW
bash /root/resipt/startup
# AKHIR STARTUP LIMITBW
exit 0
EOF

}

startupoff() {
echo " Menghapus startup di rc.local ..."
sleep 2
sed -i "/^# STARTUP LIMITBW/,/^# AKHIR STARTUP LIMITBW/d" /etc/rc.local > /dev/null
}

flushdtb() {
cat /dev/null>/root/resipt/ipt.txt
}

case $1 in
"1")
home;hapusset;addlim;exportdtb;saveper;printset;startupoff;startupon;exit
;;
esac

case $1 in
"2")
printset;exit
;;
esac

case $1 in
"3")
hapusset;startupoff;flushdtb;exit
;;
esac


#-- colors --#
#R='\e[1;31m' #RED
#G='\e[1;32m' #GREEN
#B='\e[1;34m' #BLUE
#Y='\e[1;33m' #YELLOW
#C='\e[1;36m' #CYAN
W='\e[1;37m' #WHITE
##############

#-- colors v2 --#
R='\e[31;1m' #RED
G='\e[32;1m' #GREEN
Y='\e[33;1m' #YELLOW
DB='\e[34;1m' #DARKBLUE
P='\e[35;1m' #PURPLE
LB='\e[36;1m' #LIGHTBLUE

#-- colors v3 --#
BR='\e[3;31m' #RED
BG='\e[3;32m' #GREEN
BY='\e[3;33m' #YELLOW
BDB='\e[3;34m' #DARKBLUE
BP='\e[3;35m' #PURPLE
BLB='\e[3;36m' #LIGHTBLUE

echo -e "$DB ******************************************************"
echo -e "$DB ******************************************************"
echo -e " **                                                  **"
echo -e "$DB **$R       SELAMAT DATANG DI LIMIT BANDWIDTHW         $DB**"
echo -e " **                                                  **"
echo -e "$DB ******************************************************"
echo -e "$DB **$Y         PILIH OPSI YANG SUDAH TERTERA            $DB**"
echo -e "$DB ******************************************************"
echo -e "$DB **$G        	DAFTAR :                 *PERINTAH : $DB**"
echo -e "$DB **$G ATUR LIMIT                           * limitbw 1 $DB**"
echo -e "$DB **$G LIHAT PENGATURAN TERSIMPAN           * limitbw 2 $DB**"
echo -e "$DB **$G HAPUS PENGATURAN TERSIMPAN           * limitbw 3 $DB**"
echo -e "$DB **$G KELUAR DARI MENU                     *   exit    $DB**"
echo -e "$DB ******************************************************"
echo -e "$DB **$Y             LIMIT BW  BY VITO H.S                $DB**"
echo -e "$DB **$R         https://github.com/vitoharhari           $DB**"
echo -e "$DB ******************************************************"
echo -e "$DB ******************************************************"
echo -e "$Y"
