#!/bin/bash
#This script by AlkhaNET (http://github.com/alkhanet26)

{
echo "Check Versi Limit BW"
sleep 3
wget --no-check-certificate "https://raw.githubusercontent.com/vitoharhari/limitbw/main/versi_limitbw" -O /tmp/versi_limitbw
clear
an=$(grep '* VERSION ' /tmp/versi_limitbw | cut -d '*' -f2 | cut -d ' ' -f3)
in=$(cat /usr/bin/limitbw | grep '* VERSION ' | cut -d '*' -f4 | awk 'NR==1' | cut -d ' ' -f3)
if [[ $an == $in ]]; then
echo -e "Limit BW sudah Versi terbaru"
sleep 10
else
echo -e "Sedang Update Limit BW"
sleep 2
wget --no-check-certificate "https://raw.githubusercontent.com/vitoharhari/limitbw/main/limitup" -O /usr/bin/limitup && chmod 777 /usr/bin/limitup
wget --no-check-certificate "https://raw.githubusercontent.com/vitoharhari/limitbw/main/limitbw" -O /usr/bin/limitbw && chmod 777 /usr/bin/limitbw
clear
echo -e "Selesai Update Limit BW"
sleep 10
clear
sh /usr/bin/limitbw
fi
}
