#!/bin/bash


clear

home() {
read -p "akan menampilkan database tersimpan? (y/n) : " an
if [[ $an == "y" || $an == "Y" ]]; then
echo " MENAMPILKAN DATA KODE NAMA LIMITBW TERSIMPAN"
sleep 2
cat /root/resipt/dtb
fi
sleep 2
echo ""
echo " Masukkan kode nama limitbw anda (catatan : kode nama yang sudah ada diatas tidak bisa dipakai kembali !) " 
read -p " nama : " ncode
echo " Masukkan range ip /ip anda cth: 192.168.1.1-192.168.1.254 atau 192.168.1.1 " 
read -p " ip : " ipr
echo " Masukkan limit speed download, ket : dalam KB/s (cth:100)"
read -p " speed download : " spd
echo " Masukkan limit speed upload,ket : dalam KB/s (cth:100) "
read -p " speed upload: " spu
}

hapusset() {
read -p "akan menampilkan database tersimpan? (y/n) : " an
if [[ $an == "y" || $an == "Y" ]]; then
echo " MENAMPILKAN DATA KODE NAMA LIMITBW TERSIMPAN"
sleep 2
cat /root/resipt/dtb
fi
sleep 2
echo ""
echo " Masukkan kode nama limitbw yang akan dihapus " 
read -p " nama : " ncode 
ipr2="$(cat /root/resipt/ipt$ncode.txt |grep -i ipr | cut -d= -f2 | head -n1)"
spd2="$(cat /root/resipt/ipt$ncode.txt |grep -i spd | cut -d= -f2 | head -n1)"
spu2="$(cat /root/resipt/ipt$ncode.txt |grep -i spu | cut -d= -f2 | head -n1)"

sleep 2
echo " Menghapus settingan limit bandwidth yang lama ..."
sleep 3
clear

#remove old setting iptables

#download
echo " Menghapus limit bw download"
	iptables -D FORWARD -m iprange --dst-range $ipr2 -m hashlimit --hashlimit-above $spd2+kb/s --hashlimit-mode dstip --hashlimit-name $ncode -j DROP


#upload
	iptables -D FORWARD -m iprange --src-range $ipr2 -m hashlimit --hashlimit-above $spu2+kb/s --hashlimit-mode srcip --hashlimit-name $ncode-1 -j DROP
echo " Menghapus limit bw upload"


rm /root/resipt/ipt$ncode.txt
sleep 1
sed -i "/^# AWAL $ncode/,/^# AKHIR $ncode/d" /root/resipt/startup > /dev/null
sed -i "/^# KODE : $ncode/,/^# AKHIR DATABASE $ncode/d" /root/resipt/dtb > /dev/null

}

addlim() {
#add limit bw
	#download
	iptables -I FORWARD -m iprange --dst-range $ipr -m hashlimit --hashlimit-above $spd+kb/s --hashlimit-mode dstip --hashlimit-name $ncode -j DROP
	#upload
	iptables -I FORWARD -m iprange --src-range $ipr -m hashlimit --hashlimit-above $spu+kb/s --hashlimit-mode srcip --hashlimit-name $ncode-1 -j DROP
	echo -e " Limit bandwidth telah berhasil dimasukkan"

}

saveper() {
echo " Menyimpan settingan secara permanen ..."
sleep 2

cat <<EOF>> /root/resipt/startup
# AWAL $ncode
	#download
        iptables -I FORWARD -m iprange --dst-range $ipr -m hashlimit --hashlimit-above $spd+kb/s --hashlimit-mode dstip --hashlimit-name $ncode -j DROP
        #upload
        iptables -I FORWARD -m iprange --src-range $ipr -m hashlimit --hashlimit-above $spu+kb/s --hashlimit-mode srcip --hashlimit-name $ncode-1 -j DROP
# AKHIR $ncode
EOF
sleep 1
chmod 777 /root/resipt/startup
}

exportdtb() {
echo "ipr=$ipr
spd=$spd
spu=$spu" > /root/resipt/ipt$ncode.txt
chmod 777 /root/resipt/ipt$ncode.txt
}

dtb1() {
ipr2="$(cat /root/resipt/ipt$ncode.txt |grep -i ipr | cut -d= -f2 | head -n1)"
spd2="$(cat /root/resipt/ipt$ncode.txt |grep -i spd | cut -d= -f2 | head -n1)"
spu2="$(cat /root/resipt/ipt$ncode.txt |grep -i spu | cut -d= -f2 | head -n1)"

cat <<EOF>> /root/resipt/dtb
# KODE : $ncode 
IPRANGE: $ipr2 LIMIT DOWN : $spd2 LIMIT UP : $spu2 
# AKHIR DATABASE $ncode
EOF
}

printset() {
echo " MENAMPILKAN DATA KODE LIMITBW TERSIMPAN ..."
sleep 2
cat /root/resipt/dtb
sleep 2
echo " MENAMPILKAN KONFIGURASI LIMITBW DI IPTABLES ... "
sleep 2

iptables -L --line-numbers | grep DROP | grep destination
iptables -L --line-numbers | grep DROP | grep source
}

startupon() {
echo " Memperbaharui startup di rc.local ..."
sleep 2
sed -i "/exit 0/d" /etc/rc.local
cat <<EOF>> /etc/rc.local
# STARTUP LIMITBW
bash /root/resipt/startup
# AKHIR STARTUP LIMITBW
exit 0
EOF

}

startupoff() {
echo " Menghapus startup di rc.local ..."
sleep 2
sed -i "/^# STARTUP LIMITBW/,/^# AKHIR STARTUP LIMITBW/d" /etc/rc.local > /dev/null
}

flushdtb() {
cat /dev/null>/root/resipt/ipt.txt
}

case $1 in
"1")
home;addlim;exportdtb;dtb1;saveper;printset;startupoff;startupon;exit
;;
esac

case $1 in
"2")
printset;exit
;;
esac

case $1 in
"3")
hapusset;exit
;;
esac

case $1 in
"4")
startupoff;exit
;;
esac

case $1 in
"u")
sh /usr/bin/limitup
;;
esac

#-- colors --#
#R='\e[1;31m' #RED
#G='\e[1;32m' #GREEN
#B='\e[1;34m' #BLUE
#Y='\e[1;33m' #YELLOW
#C='\e[1;36m' #CYAN
W='\e[1;37m' #WHITE
##############

#-- colors v2 --#
R='\e[31;1m' #RED
G='\e[32;1m' #GREEN
Y='\e[33;1m' #YELLOW
DB='\e[34;1m' #DARKBLUE
P='\e[35;1m' #PURPLE
LB='\e[36;1m' #LIGHTBLUE

#-- colors v3 --#
BR='\e[3;31m' #RED
BG='\e[3;32m' #GREEN
BY='\e[3;33m' #YELLOW
BDB='\e[3;34m' #DARKBLUE
BP='\e[3;35m' #PURPLE
BLB='\e[3;36m' #LIGHTBLUE

echo -e "$DB ******************************************************"
echo -e "$DB ******************************************************"
echo -e " **                                                  **"
echo -e "$DB **$R       SELAMAT DATANG DI LIMIT BANDWIDTH          $DB**"
echo -e " **                                                  **"
echo -e "$DB ******************************************************"
echo -e "$DB **$Y         PILIH OPSI YANG SUDAH TERTERA            $DB**"
echo -e "$DB ******************************************************"
echo -e "$DB **$G        	DAFTAR :                 *PERINTAH : $DB**"
echo -e "$DB **$G ATUR LIMIT                           * limitbw 1 $DB**"
echo -e "$DB **$G LIHAT PENGATURAN TERSIMPAN           * limitbw 2 $DB**"
echo -e "$DB **$G HAPUS PENGATURAN TERSIMPAN           * limitbw 3 $DB**"
echo -e "$DB **$G MATIKAN STARTUP LIMITBW              * limitbw 4 $DB**"
echo -e "$DB **$G UPDATE LIMITBW                       * limitbw u $DB**"
echo -e "$DB **$G KELUAR DARI MENU                     *   exit    $DB**"
echo -e "$DB ******************************************************"
echo -e "$DB **$Y             LIMIT BW BY * VITO H.S *             $DB**"
echo -e "$DB **$Y                 * VERSION 2.0 *                  $DB**"
echo -e "$DB **$R          https://github.com/vitoharhari          $DB**"
echo -e "$DB **$Y           ADD SOME SCRIPT * ALKHANET *           $DB**"
echo -e "$DB **$R          https://github.com/alkhanet26           $DB**"
echo -e "$DB ******************************************************"
echo -e "$DB ******************************************************"
echo -e "$Y"
